[tool.uv]
prerelease = "allow"

[tool.uv.workspace]
members = [
  "lib",
]

[tool.uv.sources]
mechanics = { workspace = true }

[dependency-groups]
dev = [
    "sphinx>=9.0.4",
    "sphinx-autodoc-typehints>=3.6.0",
    "sphinx_rtd_theme>=3.0.2",
]
